### PR TITLE
Test that localstorage is working before using it

### PR DESCRIPTION
**Pull request by edude03**
Prevents error when localStorage is used in Safari while in private mode

### CODE REVIEW

**Comment by sompylasar** [comment]
@edude03 Please reformat with tabs instead of two spaces.

**Comment by edude03** [comment]
@sompylasar thanks, I didn't notice my editor didn't set the wrong indentation. I've fixed that and pushed the change

**Comment by kieran** [comment]
:+1:

**Comment by mutewinter** [comment]
:+1:

**Comment by tinystride** [comment]
:+1:

**Comment by kieran** [comment]
any chance we can get a merge on this?

**Comment by adamjmurray** [comment]
Sure we can merge this, but please note DIY isn't actively maintaining this repository anymore.

**Comment by kieran** [comment]
Thanks @adamjmurray - good to know!

**Pull request merged**
